export enum MutationTypes {
  SET_PEOPLE = "SET_PEOPLE",
  SET_CHARACTER = "SET_CHARACTER",
  SET_FAVORITE = "SET_FAVORITE",
  SET_FAVORITES_DATA = "SET_FAVORITES_DATA",
  REMOVE_FAVORITE = "REMOVE_FAVORITE",
  UPDATE_SEARCH = "UPDATE_SEARCH",
}
